---
# Apply interface changes on OPNsense

- name: reconfigure interfaces
  ansible.builtin.uri:
    url: "{{ opnsense_api_url }}/interfaces/overview/reconfig"
    method: POST
    user: "{{ opnsense_api_key }}"
    password: "{{ opnsense_api_secret }}"
    force_basic_auth: true
    validate_certs: "{{ opnsense_validate_certs }}"
  delegate_to: localhost
