---
galaxy_info:
  role_name: opnsense_vlans
  author: Chris Deever
  description: Create VLAN sub-interfaces on OPNsense via REST API
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: OPNsense
      versions:
        - all

dependencies: []
